const LOTTERY_TYPES = {
  SSC: 'SSC',
  G11X5: '115',
  PK10: 'PK10',
  K3: 'K3'
}

const ludanMethods = [
  {id: '1', title: '总和大小', methodId: '1251', method: 'zh_dx', type: LOTTERY_TYPES.SSC},
  {id: '2', title: '总和单双', methodId: '1251', method: 'zh_ds', type: LOTTERY_TYPES.SSC},
  {id: '14', title: '万千龙虎和', methodId: '1200', method: '1v2', type: LOTTERY_TYPES.SSC},
  {id: '15', title: '万百龙虎和', methodId: '1200', method: '1v3', type: LOTTERY_TYPES.SSC},
  {id: '16', title: '万十龙虎和', methodId: '1200', method: '1v4', type: LOTTERY_TYPES.SSC},
  {id: '17', title: '万个龙虎和', methodId: '1200', method: '1v5', type: LOTTERY_TYPES.SSC},
  {id: '18', title: '千百龙虎和', methodId: '1200', method: '2v3', type: LOTTERY_TYPES.SSC},
  {id: '19', title: '千十龙虎和', methodId: '1200', method: '2v4', type: LOTTERY_TYPES.SSC},
  {id: '20', title: '千个龙虎和', methodId: '1200', method: '2v5', type: LOTTERY_TYPES.SSC},
  {id: '21', title: '百十龙虎和', methodId: '1200', method: '3v4', type: LOTTERY_TYPES.SSC},
  {id: '22', title: '百个龙虎和', methodId: '1200', method: '3v5', type: LOTTERY_TYPES.SSC},
  {id: '23', title: '十个龙虎和', methodId: '1200', method: '4v5', type: LOTTERY_TYPES.SSC},
  {id: '4', title: '万位大小', methodId: '1250', method: 'ww_dx', type: LOTTERY_TYPES.SSC, pos: 0},
  {id: '5', title: '万位单双', methodId: '1250', method: 'ww_ds', type: LOTTERY_TYPES.SSC, pos: 0},
  {id: '6', title: '千位大小', methodId: '1250', method: 'qw_dx', type: LOTTERY_TYPES.SSC, pos: 1},
  {id: '7', title: '千位单双', methodId: '1250', method: 'qw_ds', type: LOTTERY_TYPES.SSC, pos: 1},
  {id: '8', title: '百位大小', methodId: '1250', method: 'bw_dx', type: LOTTERY_TYPES.SSC, pos: 2},
  {id: '9', title: '百位单双', methodId: '1250', method: 'bw_ds', type: LOTTERY_TYPES.SSC, pos: 2},
  {id: '10', title: '十位大小', methodId: '1250', method: 'sw_dx', type: LOTTERY_TYPES.SSC, pos: 3},
  {id: '11', title: '十位单双', methodId: '1250', method: 'sw_ds', type: LOTTERY_TYPES.SSC, pos: 3},
  {id: '12', title: '个位大小', methodId: '1250', method: 'gw_dx', type: LOTTERY_TYPES.SSC, pos: 4},
  {id: '13', title: '个位单双', methodId: '1250', method: 'gw_ds', type: LOTTERY_TYPES.SSC, pos: 4},

  {id: '50', title: '总和大小', methodId: '2050', method: 'zh_dx', type: LOTTERY_TYPES.G11X5},
  {id: '51', title: '总和单双', methodId: '2050', method: 'zh_ds', type: LOTTERY_TYPES.G11X5},
  {id: '52', title: '总和尾大小', methodId: '2050', method: 'zhw_wsdx', type: LOTTERY_TYPES.G11X5},
  {id: '53', title: '总和尾单双', methodId: '2050', method: 'zhw_wsds', type: LOTTERY_TYPES.G11X5},
  {id: '55', title: '龙虎', methodId: '2053', method: 'wg_lhh', type: LOTTERY_TYPES.G11X5},
  {id: '56', title: '第一位大小', methodId: '2051', method: 'ww_dx', type: LOTTERY_TYPES.G11X5, pos: 0},
  {id: '57', title: '第一位单双', methodId: '2051', method: 'ww_ds', type: LOTTERY_TYPES.G11X5, pos: 0},
  {id: '58', title: '第二位大小', methodId: '2051', method: 'qw_dx', type: LOTTERY_TYPES.G11X5, pos: 1},
  {id: '59', title: '第二位单双', methodId: '2051', method: 'qw_ds', type: LOTTERY_TYPES.G11X5, pos: 1},
  {id: '60', title: '第三位大小', methodId: '2051', method: 'bw_dx', type: LOTTERY_TYPES.G11X5, pos: 2},
  {id: '61', title: '第三位单双', methodId: '2051', method: 'bw_ds', type: LOTTERY_TYPES.G11X5, pos: 2},
  {id: '62', title: '第四位大小', methodId: '2051', method: 'sw_dx', type: LOTTERY_TYPES.G11X5, pos: 3},
  {id: '63', title: '第四位单双', methodId: '2051', method: 'sw_ds', type: LOTTERY_TYPES.G11X5, pos: 3},
  {id: '64', title: '第五位大小', methodId: '2051', method: 'gw_dx', type: LOTTERY_TYPES.G11X5, pos: 4},
  {id: '65', title: '第五位单双', methodId: '2051', method: 'gw_ds', type: LOTTERY_TYPES.G11X5, pos: 4},
  {id: '67', title: '万千龙虎和', methodId: '2035', method: '1v2', type: LOTTERY_TYPES.G11X5},
  {id: '68', title: '万百龙虎和', methodId: '2035', method: '1v3', type: LOTTERY_TYPES.G11X5},
  {id: '69', title: '万十龙虎和', methodId: '2035', method: '1v4', type: LOTTERY_TYPES.G11X5},
  {id: '70', title: '万个龙虎和', methodId: '2035', method: '1v5', type: LOTTERY_TYPES.G11X5},
  {id: '71', title: '千百龙虎和', methodId: '2035', method: '2v3', type: LOTTERY_TYPES.G11X5},
  {id: '72', title: '千十龙虎和', methodId: '2035', method: '2v4', type: LOTTERY_TYPES.G11X5},
  {id: '73', title: '千个龙虎和', methodId: '2035', method: '2v5', type: LOTTERY_TYPES.G11X5},
  {id: '74', title: '百十龙虎和', methodId: '2035', method: '3v4', type: LOTTERY_TYPES.G11X5},
  {id: '75', title: '百个龙虎和', methodId: '2035', method: '3v5', type: LOTTERY_TYPES.G11X5},
  {id: '76', title: '十个龙虎和', methodId: '2035', method: '4v5', type: LOTTERY_TYPES.G11X5},

  {id: '100', title: '冠亚和大小', methodId: '4050', method: 'zh_dx', type: LOTTERY_TYPES.PK10},
  {id: '101', title: '冠亚和单双', methodId: '4050', method: 'zh_ds', type: LOTTERY_TYPES.PK10},
  {id: '102', title: '冠军大小', methodId: '4053', method: 'ww_dx', type: LOTTERY_TYPES.PK10, pos: 0},
  {id: '103', title: '冠军单双', methodId: '4053', method: 'ww_ds', type: LOTTERY_TYPES.PK10, pos: 0},
  {id: '104', title: '亚军大小', methodId: '4053', method: 'qw_dx', type: LOTTERY_TYPES.PK10, pos: 1},
  {id: '105', title: '亚军单双', methodId: '4053', method: 'qw_ds', type: LOTTERY_TYPES.PK10, pos: 1},
  {id: '106', title: '季军大小', methodId: '4053', method: 'bw_dx', type: LOTTERY_TYPES.PK10, pos: 2},
  {id: '107', title: '季军单双', methodId: '4053', method: 'bw_ds', type: LOTTERY_TYPES.PK10, pos: 2},
  {id: '108', title: '第四位大小', methodId: '4053', method: 'sw_dx', type: LOTTERY_TYPES.PK10, pos: 3},
  {id: '109', title: '第四位单双', methodId: '4053', method: 'sw_ds', type: LOTTERY_TYPES.PK10, pos: 3},
  {id: '110', title: '第五位大小', methodId: '4053', method: 'gw_dx', type: LOTTERY_TYPES.PK10, pos: 4},
  {id: '111', title: '第五位单双', methodId: '4053', method: 'gw_ds', type: LOTTERY_TYPES.PK10, pos: 4},
  {id: '112', title: '冠军vs第十名龙虎', methodId: '4011', method: '1v10', type: LOTTERY_TYPES.PK10},
  {id: '113', title: '亚军vs第九名龙虎', methodId: '4011', method: '2v9', type: LOTTERY_TYPES.PK10},
  {id: '114', title: '季军vs第八名龙虎', methodId: '4011', method: '3v8', type: LOTTERY_TYPES.PK10},
  {id: '115', title: '第四名vs第七名龙虎', methodId: '4011', method: '4v7', type: LOTTERY_TYPES.PK10},
  {id: '116', title: '第五名vs第六名龙虎', methodId: '4011', method: '5v6', type: LOTTERY_TYPES.PK10},

  {id: '200', title: '大小', methodId: '5018', method: 'zh_dx', type: LOTTERY_TYPES.K3},
  {id: '201', title: '单双', methodId: '5018', method: 'zh_ds', type: LOTTERY_TYPES.K3}

]

export default ludanMethods
